disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Hackie~G"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo ="images/8.jpeg"
  # secondaryLogo = "img/secondary-logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Bonnie Gitonga"
  email = "bonfaceg303@gmail.com"
  image = "images/5.jpeg"
  imageQuality = 96
  headline = "Cybersecurity Researcher"
  bio = "Hey you!!"
  links = [
    { email = "mailto:hello@your_domain.com" },
    # { link = "https://link-to-some-website.com/" },
    # { dev = "https://dev.to/username" },
    { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    { linkedin = "https://linkedin.com/in/username" },
    { medium = "https://medium.com/username" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://www.threads.net/@username" },
    # { tiktok = "https://tiktok.com/@username" },
    { x-twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
  ]
